### ISSUE TITLE
page.evaluate: TypeError: Cannot read properties of undefined (reading 'run')

### ISSUE THREAD

**Issue by thomasfischer-his** [a11ywatch/kayle#18]
Using a setup similar as described in https://github.com/a11ywatch/a11ywatch/issues/65, I encounter a `TypeError` when scanning https://www.bolagsverket.se/ using either `axe` or `htmlcs` as runner.

The scan is run using the latest [Docker container 'a11ywatch'](https://hub.docker.com/r/a11ywatch/a11ywatch). The container is launched via Podman as follows:

```bash
podman run --rm --interactive --add-host chrome:127.0.0.2 -p 3280:3280/tcp -p 50050:50050/tcp -p 50051:50051/tcp -p 50052:50052/tcp -p 50053:50053/tcp -p 50054:50054/tcp -p 9222:9222/tcp docker.io/a11ywatch/a11ywatch
```

Then, a scan is triggered by the following curl invocation:

```bash
curl --max-time 30 --location --request POST http://localhost:3280/api/scan -H 'Accept-Charset: utf-8' --header 'Content-Type: application/json' --data-raw '{ "url": "https://www.bolagsverket.se/", "runners": ["axe"] }'
```

In the terminal where the container was started (not where curl is running), the following output is generated after the start of curl:

```
page.evaluate: TypeError: Cannot read properties of undefined (reading 'run')
    at eval (eval at evaluate (:208:30), <anonymous>:1:90)
    at UtilityScript.evaluate (<anonymous>:210:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at o (/usr/src/app/node_modules/kayle/build/kayle.js:1:354)
    at s (/usr/src/app/node_modules/kayle/build/kayle.js:1:715)
    at async g (/usr/src/app/node_modules/kayle/build/kayle.js:1:1685)
```

On the curl side, valid JSON output is returned, but no accessibility issue is reported:

```json
{"data":{"domain":"www.bolagsverket.se","url":"https://www.bolagsverket.se/","pageLoadTime":{"duration":0,"durationFormated":"Cached/Extremely Fast"},"lastScanDate":"2023-11-17T09:15:10.162Z","issues":[],"issuesInfo":{"possibleIssuesFixedByCdn":0,"totalIssues":0,"issuesFixedByCdn":0,"errorCount":0,"warningCount":0,"noticeCount":0,"accessScore":0,"issueMeta":{"skipContentIncluded":true}},"online":true},"success":true,"code":200,"message":""}
```

**Comment by j-mendez** [comment]
Closing not reproducible. Browser could have been closed mid flight request.

**Comment by thomasfischer-his** [comment]
Yes, I can also no longer reproduce this issue.
